# Generated by Django 5.0.6 on 2024-07-09 20:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма покупки')),
                ('detail', models.TextField(default='История отсутствует т.к покупка совершалась в магазине', verbose_name='Инфопрмация о покупке')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название приза')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('unit', models.CharField(max_length=64, verbose_name='Еденица измерения товара (кг/шт)')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('is_stock', models.BooleanField(default=False, verbose_name='Есть ли акция на этот товар?')),
                ('is_send_message', models.BooleanField(default=False, verbose_name='Нужно ли сделать рассылку пользователям?')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='кол-во')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, verbose_name='ID чата телеграмма')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя')),
                ('birthday', models.CharField(blank=True, max_length=32, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Бонусы')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Является ли пользователь продавцом')),
                ('can_use_lottery', models.BooleanField(default=False, verbose_name='Может ли использовать лоотерею?')),
                ('last_lottery_time', models.DateTimeField(default=datetime.datetime(2024, 7, 7, 23, 23, 52, 313088), verbose_name='Последняя дата использования лотереи')),
                ('cart', models.ManyToManyField(blank=True, to='app.cart', verbose_name='Корзина')),
                ('history', models.ManyToManyField(blank=True, to='app.history', verbose_name='История покупок')),
            ],
        ),
    ]
