# Generated by Django 5.0.6 on 2024-07-10 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=1000, verbose_name='Бонус')),
            ],
        ),
        migrations.AddField(
            model_name='lottery',
            name='rare',
            field=models.IntegerField(default=1, verbose_name='Частота выпадения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 15, 17, 0, 835541), verbose_name='Последняя дата использования лотереи'),
        ),
    ]
