# Generated by Django 5.0.6 on 2024-07-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bonus_lottery_rare_alter_user_last_lottery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 15, 35, 50, 176092), verbose_name='Последняя дата использования лотереи'),
        ),
    ]
