# Generated by Django 5.0.6 on 2024-07-11 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_last_lottery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название ранга')),
                ('price', models.IntegerField(default=0, verbose_name='Сумма, до которой действителен ранг')),
                ('sale', models.IntegerField(verbose_name='Скидка на этом ранге')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 15, 46, 2, 81230), verbose_name='Последняя дата использования лотереи'),
        ),
    ]
