# Generated by Django 5.0.6 on 2024-07-11 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rank_alter_user_last_lottery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='birthday_bonus',
            field=models.IntegerField(default=1000, verbose_name='Бонус на день рождения'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus',
            field=models.IntegerField(default=1000, verbose_name='Приветственный бонус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 16, 0, 21, 480423), verbose_name='Последняя дата использования лотереи'),
        ),
    ]
