# Generated by Django 5.0.6 on 2024-07-27 22:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bonus_birthday_bonus_alter_bonus_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание акции')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('unit', models.CharField(max_length=64, verbose_name='Еденица измерения товара (кг/шт)')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('is_send_message', models.BooleanField(default=False, verbose_name='Нужно ли сделать рассылку пользователям?')),
                ('need_add_to_cart', models.BooleanField(default=False, verbose_name='Нужно ли сразу кидать товар в корзину?')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_send_message',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='need_add_to_cart',
            field=models.BooleanField(default=False, verbose_name='Нужно ли сразу кидать товар в корзину?'),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.FloatField(default=1, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 1, 39, 49, 236662), verbose_name='Последняя дата использования лотереи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Общая сумма покупок'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Собирается', max_length=128, verbose_name='Статус заказа')),
                ('date', models.CharField(max_length=32, verbose_name='Дата и время, на которое сделан заказ')),
                ('products', models.ManyToManyField(blank=True, to='app.cart', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, to='app.orders', verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='cart',
            name='stocks',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='app.stocks', verbose_name='Акция'),
            preserve_default=False,
        ),
    ]
