# Generated by Django 5.0.6 on 2024-07-27 22:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stocks_remove_product_is_send_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='stocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stocks', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lottery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 1, 40, 42, 661165), verbose_name='Последняя дата использования лотереи'),
        ),
    ]
